---
name: Update sdk
on: push
jobs:
  update-sdk:
    name: Update sdk
    runs-on: ubuntu-latest
    if: github.repository == 'networkservicemesh/api'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: networkservicemesh/sdk
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Update sdk locally
        run: |
          GOPROXY=direct go get -u github.com/networkservicemesh/api
          go mod tidy
          git diff
      - name: Push update to sdk
        run: |
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git add go.mod go.sum
          git commit -s -m "Update go.mod and go.sum to latest version from networkservicemesh/api@master"
          git checkout -b update/api-gomod
          git push -f origin update/api-gomod
